---
- hosts: localhost
  connection: local
  gather_facts: yes

  vars_files:
    - vars/config.yml

  tasks:
  - name: internal networks
    os_network:
      state: present
      name: '{{item.name}}'
      external: '{{item.external}}'
      shared: no
      project: '{{item.project}}'
    with_items:
      - '{{int_networks}}'

  - name: internal subnets
    os_subnet:
      state: present
      network_name: '{{item.network_name}}'
      name: '{{item.name}}'
      cidr: '{{item.cidr}}'
      dns_nameservers: '{{item.dns_nameservers}}'
    with_items:
      - '{{int_subnets}}'

  - name: routers
    os_router:
      project: '{{project.name}}'
      state: present
      name: '{{item.name}}'
      network: '{{item.network}}'
      interfaces: '{{item.interfaces | default("")}}'
    with_items:
      - '{{routers}}'
    ignore_errors: true

