---
- hosts: localhost
  connection: local
  gather_facts: yes

  vars_files:
    - vars/config.yml

  tasks:
  - name: new projecct
    os_project:
      state: present
      name: '{{project.name}}'
      description: "project for {{project.name}}"
      enabled: true
      domain_id: Default

