---
- hosts: localhost
  connection: local
  gather_facts: yes

  vars_files:
    - vars/config.yml

  tasks:
  - name: quotas
    os_quota:
      name: '{{item.name}}'
      cores: '{{item.cores}}'
      ram: '{{item.ram}}'
      volumes: '{{item.volumes}}'
    with_items:
      - '{{quotas}}'
