---
- hosts: localhost
  connection: local
  gather_facts: yes

  vars_files:
    - vars/config.yml

  tasks:
  - name: security groups
    os_security_group:
      auth: '{{auth}}'
      state: present
      name: '{{item.name}}'
      description: '{{item.description}}'
    with_items:
      - '{{security_groups}}'

  - name: rules
    os_security_group_rule:
      auth: '{{auth}}'
      security_group: '{{item.security_group}}'
      protocol: '{{item.protocol}}'
      port_range_min: '{{item.port_range_min}}'
      port_range_max: '{{item.port_range_max}}'
      remote_ip_prefix: '{{item.remote_ip_prefix}}'
    when: item.remote_ip_prefix is defined
    with_items:
      - '{{rules}}'

  - name: rules
    os_security_group_rule:
      auth: '{{auth}}'
      security_group: '{{item.security_group}}'
      protocol: '{{item.protocol}}'
      port_range_min: '{{item.port_range_min}}'
      port_range_max: '{{item.port_range_max}}'
      remote_group: '{{item.remote_group}}'
    when: item.remote_group is defined
    with_items:
      - '{{rules}}'

